<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-03-07 10:30
=======
# Generated by Django 4.0.3 on 2022-03-05 15:48
>>>>>>> d99c0f7a7f2a4fa877b02d6f8dc52681d5de9219

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
